---
# author: XuFei

# 1. 进行发布前检查，发布所需要的内容不存在时停止执行并抛出错误信息
- import_tasks: check.yml
  when: not deploy_rollback

# 2. 备份老的war包
- import_tasks: backup.yml
  when: not deploy_rollback  

# 3. 发布代码到目标服务器并启动程序
- import_tasks: deploy.yml
  when: not deploy_rollback
